name: Desktop

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:

      - name: Start Desktop
        run: |
          docker run -d --name desktop -p 6080:80 dorowu/ubuntu-desktop-lxde-vnc
          sleep 20
          curl -I http://localhost:6080

      - name: Install SSH
        run: |
          sudo apt update
          sudo apt install -y openssh-client

      - name: Create Tunnel
        run: |
          ssh -o StrictHostKeyChecking=no -R 80:localhost:6080 ssh.localhost.run
