name: Desktop

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:

      - name: Start Desktop Container
        run: |
          docker run -d -p 6080:80 dorowu/ubuntu-desktop-lxde-vnc

      - name: Install Cloudflare Tunnel
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

      - name: Open Tunnel
        run: |
          cloudflared tunnel --url http://localhost:6080 > tunnel.log 2>&1 &
          sleep 20
          cat tunnel.log
          sleep 20000
