name: Desktop

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:

      - name: Start Desktop
        run: |
          docker run -d --name desktop -p 6080:80 dorowu/ubuntu-desktop-lxde-vnc
          
          echo "Waiting for desktop..."
          
          for i in {1..30}; do
            curl -I http://localhost:6080 && break
            sleep 2
          done
          
          docker ps

      - name: Install cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

      - name: Start Tunnel
        run: |
          cloudflared tunnel --url http://localhost:6080
